// Generated by Wrangler on Mon Oct 07 2024 17:51:33 GMT+0530 (India Standard Time)
// by running `wrangler types`

interface Env {
	BLOGGER_API_KEY: string;
	CONVERT_KIT_API_KEY: string;
	CONVERT_KIT_FORM_ID: string;
}
